# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {e via RSS{ site.myvariable }}.

title: Issa Memari
email: issa@memari.me
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my personal website! My name is Issa Memari.
  I'm a machine learning engineer with 5 years of experience.
  I'm passionate about software and AI and I'm always seeking to
  strengthen my knowledge and technical skills in these fields.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Fields minima uses, but are not defaulted with the jekyll new command.
# Author is the default for posts, the Atom feed, and is used in the footer.
author: Issa Memari

# avatar
avatar: /images/avatar.png

# Build settings
# Removed minima theme as it is now a regular theme
# theme: minima
plugins:
  - jekyll-feed

markdown: kramdown
kramdown:
   math_engine: mathjax

github_comments_repository:  issamemari/issamemari.github.io
